modLoader="javafml" #mandatory
loaderVersion="[34,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
issueTrackerURL="https://github.com/JustDoom/Just-Needed-Forge/issues" #optional
[[mods]] #mandatory
modId="justneeded" #mandatory
version="1.16.4-1.0.0" #mandatory
displayName="Just Needed" #mandatory
#updateJSONURL="http://myurl.me/" #optional
#displayURL="http://example.com/" #optional
logoFile="logo.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="JustDoom" #optional
description='''
This mod adds items, blocks, recipes that are just needed to be in minecraft!
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.justneeded]] #optional
# the modid of the dependency
modId="forge" #mandatory
# Does this dependency have to exist - if not, ordering below must be specified
mandatory=true #mandatory
# The version range of the dependency
versionRange="[34,)" #mandatory
# An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
ordering="NONE"
# Side this dependency is applied on - BOTH, CLIENT or SERVER
side="BOTH"
# Here's another dependency
[[dependencies.justneeded]]
modId="minecraft"
mandatory=true
versionRange="[1.16.4]"
ordering="NONE"
side="BOTH"