modLoader="javafml" #mandatory

loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

mandatoryissueTrackerURL="https://github.com/JustDoom/Just-Needed-1.14-Forge/issues" #optional

[[mods]] #mandatory

modId="justneeded" #mandatory

version="1.15.2-1.0.3" #mandatory

displayName="Just Needed" #mandatory

#updateJSONURL="http://myurl.me/" #optional

#displayURL="http://example.com/" #optional

logoFile="logo.png" #optional

#credits="Thanks for this example mod goes to Java" #optional

authors="JustDoom" #optional
description='''
This mod adds items, blocks, recipes that are just needed to be in minecraft!
'''
[[dependencies.justneeded]] #optional
modId="forge"
mandatory=true #mandatory
versionRange="[31,)" #mandatory
ordering="NONE"
side="BOTH"

[[dependencies.justneeded]]
modId="minecraft"
mandatory=true
versionRange="[1.15.2]"
ordering="NONE"
side="BOTH"
